### PR TITLE
Master

### PR DESCRIPTION
**Pull request by katrinako**
event list-group + team list-group position

### CODE REVIEW

**Comment by poonvanessa** [comment]
What have you done??

**Comment by katrinako** [comment]
I've add a list-group2 in event.html, and change the position of list-group in team.html.

**Comment by wai2016** [comment]
That's great.

**Comment by p-wong1124** [comment]
I have moved the activityDetailTemp to /app/detailTemp folder. #29 
So might be have a duplicated copy if you add a  in it. (but it is fine as we can locate and delete 😛 )

**Comment by p-wong1124** [comment]
is it having all UI updates together with both Vanessa and Katrina version?? 😄

**Comment by katrinako** [comment]
HELP

**Pull request merged**
