### PR TITLE
Change firebase to our group firebase

### PR DESCRIPTION
**Pull request by RaymondWongCH**

### CODE REVIEW

**Comment by wai2016** [comment]
Good.

**Comment by p-wong1124** [comment]
Today I also wondering why can't I login to site by firebase :)

Good ar if change to our common site.js :)

**Comment by robbieyang** [comment]
@p-wong1124 Which firebase you are using when doing test of your features in your local repo?

**Comment by p-wong1124** [comment]
@robbieyang  #70 there is a site.js which mounted to one's firebase.
Now when I put back site.js (origin) the login works 😄

**Pull request merged**
