### PR TITLE
Move detail page to a folder & changed member.js

### PR DESCRIPTION
**Pull request by p-wong1124**
As I have changed structure.
Before
events as in the root directory.
Now
events are put in the /event/
also,
I have edited the member to adopt the changes :)

### CODE REVIEW

**Comment by robbieyang** [comment]
It is good, the structure is more clear than before. However, the issue I have raised #11 should be considered

**Comment by RaymondWongCH** [comment]
It is great to have the structure modified better.

**Comment by wai2016** [comment]
Good.

**Comment by poonvanessa** [comment]
NICE

**Comment by p-wong1124** [comment]
has updated to the current version
@RaymondWongCH  's changes in team.js are kept :)

**Comment by wai2016** [comment]
My pull-request is merged and I should only add one line of code.
Should be easy to solve the conflicts. =]

**Comment by p-wong1124** [comment]
merged before really merge to the master ;)
for safety merge ( 🙈  )

**Pull request merged**
