### PR TITLE
Finally we have UI. YEAH~~~

### PR DESCRIPTION
**Pull request by poonvanessa**
Push my UI la hahaha

### CODE REVIEW

**Comment by wai2016** [comment]
I think you have to add back these four buttons and include the libraries like firebase, and js file i.e. site.js and index.js.

```
<button id="btn_admin" type="button" class="btn btn-primary" >Administrator</button>
<button id="btn_leader" type="button" class="btn btn-primary" >Team Leader</button>
<button id="btn_member" type="button" class="btn btn-primary" >Member</button>
<button disabled class="btn btn-primary" id="quickstart-sign-in" type="button">Log in with Facebook</button>        
```

**Comment by poonvanessa** [comment]
Something goes wrong. Sorry about that :-(

**Comment by poonvanessa** [comment]
I think the UI is fine so far. Should we merge them?

**Comment by robbieyang** [comment]
The UI is great! I think it is ok to merge. However, the UI logic should be explained in details and discuss how to apply features to UI.

**Comment by katrinako** [comment]
I've improved some parts of the UI.

**Comment by poonvanessa** [comment]
Great. I'll merge it. 👍

**Pull request merged**
